apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: robofriends-pwa
  description: A progressive web app for friends
  annotations:
    github.com/project-slug: LogosCode/robofriends_pwa
    backstage.io/techdocs-ref: dir:.
  tags:
    -  react
    -  pwa
    -  javascript
spec:
  type: website
  lifecycle: production
  owner: logoscode
